name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./install-entando
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './install-entando/package.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

